# Generated by Django 4.1.10 on 2023-08-23 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('citta', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=255)),
                ('immagine', models.ImageField(upload_to='utenti/')),
                ('git', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('web', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('contenuto', models.TextField()),
                ('data_pubblicazione', models.DateTimeField(default=django.utils.timezone.now)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.utente')),
                ('categorie', models.ManyToManyField(to='Portfolio.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valore', models.CharField(max_length=255)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.utente')),
            ],
        ),
    ]
